.MODEL SMALL
DISPLAY MACRO, MSG
LEA DX, MSG
MOV AH, 09H
INT 21H
ENDM
.DATA
MSG1 DB 0DH,0AH, "ENTER STRING 1 $"
MSG2 DB 0DH,0AH, "ENTER STRING 2 $"
MSG3 DB 0DH,0AH, "ENTERED STRINGS ARE SAME $"
MSG4 DB 0DH,0AH, "ENTERED STRINGS ARE NOT SAME $"
STR1 DB 10H DUP(0)
STR2 DB 10H DUP(0)
LEN1 DW 0
LEN2 DW 0
.CODE
MOV AX,@DATA
MOV DS,AX
DISPLAY MSG1
MOV SI,00H
BACK1 : MOV AH,01H
        INT 21H
        CMP AL, 0DH
        JZ NEXT1
        MOV STR1[SI], AL
        INC SI
        INC LEN1
        JMP BACK1
NEXT1 : DISPLAY MSG2
        MOV DI,00H
        JMP BACK2
BACK2 : MOV AH,01H
        INT 21H
        CMP AL,0DH
        JZ NEXT2
        MOV STR2[DI], AL
        INC DI
        INC LEN2
        JMP BACK2
NEXT2 : MOV SI, LEN1
        MOV DI, LEN2
        CMP SI, DI
        JNZ NOTSAME
        MOV SI,00H
        MOV DI,00H
        CLD
        JMP BACK3
BACK3 : MOV BL,STR1[SI]
        CMP BL,STR2[DI]
        JNZ NOTSAME
        LOOP BACK3
        DISPLAY MSG3
        JMP LAST
NOTSAME:DISPLAY MSG4
LAST :MOV AH,4CH
      INT 21H
END


